# Generated by Django 2.0.6 on 2018-07-22 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_list_addedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=32000),
            preserve_default=False,
        ),
    ]
