# Generated by Django 2.0.6 on 2018-07-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0007_remove_list_detailcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name=django.db.models.deletion.SET_NULL),
        ),
    ]
