# Generated by Django 2.0.6 on 2018-07-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0008_list_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='detail',
            field=models.TextField(default='No details has been added.'),
        ),
    ]
