# Generated by Django 2.0.6 on 2018-07-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0009_auto_20180724_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='detail',
            field=models.CharField(blank=True, default='No details has been added.', max_length=3200),
        ),
    ]
